/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ibcn.unl.edu.ec.manage_wallet;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
}
